baseURL = "https://untitled-hugo-doc.netlify.app/"
languageCode = "en-us"
title = "UNTITLED-Hugo-Doc"
theme = "utitled-hugo-doc"

[params]

  # Hide content from sidebar
  menu_exclusion = [
    "blog",
    "post",
  ]